#!/usr/bin/env perl

use Class::Inspector;
use lib qw(lib);


package Foo::Bar;
sub foo   { "foo" }
sub bar   { "bar" }
sub hello { "hello" }
sub hill  { "hill" }


package Less::More;
sub less { "less" }
sub more { "more" }


package Hello;


package main;
use Class::Implant;
implant qw(Foo::Bar Less::More), { into => "Hello", match => qr{h\w+} };

for (qw(foo bar less more hello hill)) {
  eval qq{ print Hello->$_, "\n" };
}

if ( Hello->can("foo") ) {
  print "can_ok foo()\n";
} else {
  print "cannot_ok foo()\n";
}

print Hello->can("foo"), "\n";



